#ifndef LIGHTMODBUS_LIBCONF_H
#define LIGHTMODBUS_LIBCONF_H

#define LIGHTMODBUS_VERSION ""
#define LIGHTMODBUS_GIT_VERSION "751eb1-dirty"


#define LIGHTMODBUS_LITTLE_ENDIAN

#define LIGHTMODBUS_SLAVE_BASE
#define LIGHTMODBUS_F01S
#define LIGHTMODBUS_F02S
#define LIGHTMODBUS_F03S
#define LIGHTMODBUS_F04S
#define LIGHTMODBUS_F05S
#define LIGHTMODBUS_F06S
#define LIGHTMODBUS_F15S
#define LIGHTMODBUS_F16S

#define LIGHTMODBUS_STATIC_MEM_SLAVE_RESPONSE 300

#endif